"""Controlled skill ontology.

Each entry: canonical name -> (category, aliases, implies, related)

* aliases  – alternative spellings that normalise to the canonical name (EXACT / alias match).
* implies  – broader skills that evidence of this skill genuinely demonstrates
             (e.g. PyTorch implies Deep Learning). Used for SEMANTIC matches.
* related  – adjacent technologies that are NOT a match (e.g. Docker vs Kubernetes).
             Used only to report RELATED_BUT_NOT_MATCH, never to award credit.
"""

from __future__ import annotations

SkillSpec = tuple[str, list[str], list[str], list[str]]

SKILLS: dict[str, SkillSpec] = {
    # ---------------------------------------------------------------- programming
    "Python": ("programming", ["python3", "python 3", "py"], [], ["Cython"]),
    "JavaScript": ("programming", ["js", "javascript", "ecmascript", "es6"], [], ["TypeScript"]),
    "TypeScript": ("programming", ["ts", "typescript"], ["JavaScript"], []),
    "Java": ("programming", ["java 8", "java 11", "java 17", "core java"], [], ["Kotlin", "Scala"]),
    "Kotlin": ("programming", [], [], ["Java"]),
    "Scala": ("programming", [], [], ["Java", "Apache Spark"]),
    "C": ("programming", ["c language", "ansi c"], [], ["C++"]),
    "C++": ("programming", ["cpp", "c plus plus", "c++11", "c++17"], [], ["C", "Rust"]),
    "C#": ("programming", ["c sharp", "csharp"], [], [".NET"]),
    "Go": ("programming", ["golang"], [], ["Rust"]),
    "Rust": ("programming", [], [], ["C++", "Go"]),
    "Ruby": ("programming", [], [], ["Ruby on Rails"]),
    "PHP": ("programming", [], [], ["Laravel"]),
    "Swift": ("programming", [], [], ["iOS"]),
    "R": ("programming", ["r language", "r programming"], [], ["Python"]),
    "MATLAB": ("programming", [], [], []),
    "Bash": ("programming", ["shell scripting", "shell script", "bash scripting", "shell"], [], ["Linux"]),
    "SQL": ("databases", ["structured query language", "sql queries"], [], ["PostgreSQL", "MySQL"]),
    "Dart": ("programming", [], [], ["Flutter"]),
    # ---------------------------------------------------------------- web / backend frameworks
    "FastAPI": ("frameworks", ["fast api"], ["REST APIs", "Python"], ["Flask", "Django"]),
    "Django": ("frameworks", ["django rest framework", "drf"], ["Python"], ["Flask", "FastAPI"]),
    "Flask": ("frameworks", [], ["Python"], ["FastAPI", "Django"]),
    "Node.js": ("frameworks", ["node", "nodejs", "node js"], ["JavaScript"], ["Express.js"]),
    "Express.js": ("frameworks", ["express", "expressjs"], ["Node.js"], ["NestJS"]),
    "NestJS": ("frameworks", ["nest.js", "nestjs"], ["Node.js", "TypeScript"], ["Express.js"]),
    "Spring Boot": ("frameworks", ["spring", "springboot", "spring framework"], ["Java"], []),
    "Ruby on Rails": ("frameworks", ["rails", "ror"], ["Ruby"], []),
    "Laravel": ("frameworks", [], ["PHP"], []),
    ".NET": ("frameworks", ["dotnet", "asp.net", ".net core", "asp.net core"], [], ["C#"]),
    "GraphQL": ("frameworks", [], [], ["REST APIs"]),
    "REST APIs": ("frameworks", ["rest", "restful", "rest api", "restful apis", "restful api", "rest apis"], [], ["GraphQL", "gRPC"]),
    "gRPC": ("frameworks", ["grpc"], [], ["REST APIs"]),
    "Microservices": ("frameworks", ["microservice", "micro-services", "microservices architecture"], [], []),
    "Celery": ("frameworks", [], ["Python"], ["RabbitMQ", "Redis"]),
    "Pydantic": ("frameworks", [], ["Python"], []),
    "SQLAlchemy": ("frameworks", [], ["Python", "SQL"], []),
    # ---------------------------------------------------------------- frontend
    "React": ("frontend", ["react.js", "reactjs", "react js"], ["JavaScript"], ["Next.js", "Vue.js", "Angular"]),
    "Next.js": ("frontend", ["nextjs", "next js"], ["React"], []),
    "Vue.js": ("frontend", ["vue", "vuejs"], ["JavaScript"], ["React"]),
    "Angular": ("frontend", ["angularjs", "angular.js"], ["TypeScript"], ["React"]),
    "Svelte": ("frontend", [], ["JavaScript"], []),
    "HTML": ("frontend", ["html5"], [], ["CSS"]),
    "CSS": ("frontend", ["css3"], [], ["HTML", "Tailwind CSS"]),
    "Tailwind CSS": ("frontend", ["tailwind", "tailwindcss"], ["CSS"], []),
    "Redux": ("frontend", [], ["React"], []),
    "Flutter": ("frontend", [], ["Dart"], ["React Native"]),
    "React Native": ("frontend", [], ["React"], ["Flutter"]),
    "iOS": ("frontend", ["ios development"], [], ["Swift"]),
    "Android": ("frontend", ["android development"], [], ["Kotlin"]),
    # ---------------------------------------------------------------- databases
    "PostgreSQL": ("databases", ["postgres", "postgresql database", "psql", "postgre"], ["SQL"], ["MySQL"]),
    "MySQL": ("databases", ["my sql"], ["SQL"], ["PostgreSQL"]),
    "SQLite": ("databases", [], ["SQL"], []),
    "Microsoft SQL Server": ("databases", ["sql server", "mssql", "ms sql", "t-sql"], ["SQL"], []),
    "Oracle Database": ("databases", ["oracle db", "oracle", "pl/sql"], ["SQL"], []),
    "MongoDB": ("databases", ["mongo", "mongo db"], ["NoSQL"], []),
    "Redis": ("databases", [], ["NoSQL"], ["Memcached"]),
    "Cassandra": ("databases", ["apache cassandra"], ["NoSQL"], []),
    "DynamoDB": ("databases", ["dynamo db", "amazon dynamodb"], ["NoSQL", "AWS"], []),
    "Elasticsearch": ("databases", ["elastic search", "elk", "opensearch"], [], ["Solr"]),
    "NoSQL": ("databases", ["no sql", "nosql databases"], [], []),
    "Neo4j": ("databases", [], [], []),
    "Snowflake": ("data", [], ["SQL"], ["BigQuery", "Redshift"]),
    "BigQuery": ("data", ["google bigquery"], ["SQL", "GCP"], ["Snowflake"]),
    "Redshift": ("data", ["amazon redshift"], ["SQL", "AWS"], ["Snowflake"]),
    "Supabase": ("databases", [], ["PostgreSQL"], []),
    "Firebase": ("databases", [], [], []),
    # ---------------------------------------------------------------- vector / retrieval
    "Vector Databases": ("ai_ml", ["vector database", "vector db", "vector store", "vector stores", "vector search"], [], []),
    "Qdrant": ("ai_ml", [], ["Vector Databases"], ["Pinecone", "Weaviate", "Milvus"]),
    "Pinecone": ("ai_ml", [], ["Vector Databases"], ["Qdrant"]),
    "Weaviate": ("ai_ml", [], ["Vector Databases"], ["Qdrant"]),
    "Milvus": ("ai_ml", [], ["Vector Databases"], ["Qdrant"]),
    "ChromaDB": ("ai_ml", ["chroma", "chroma db"], ["Vector Databases"], ["Qdrant"]),
    "FAISS": ("ai_ml", ["faiss"], ["Vector Databases"], []),
    "pgvector": ("ai_ml", [], ["Vector Databases", "PostgreSQL"], []),
    # ---------------------------------------------------------------- cloud
    "AWS": ("cloud", ["amazon web services", "aws cloud"], ["Cloud Computing"], ["GCP", "Azure"]),
    "GCP": ("cloud", ["google cloud", "google cloud platform"], ["Cloud Computing"], ["AWS", "Azure"]),
    "Azure": ("cloud", ["microsoft azure", "azure cloud"], ["Cloud Computing"], ["AWS", "GCP"]),
    "Cloud Computing": ("cloud", ["cloud", "cloud platforms", "cloud services"], [], []),
    "AWS Lambda": ("cloud", ["lambda"], ["AWS", "Serverless"], []),
    "Amazon S3": ("cloud", ["s3", "aws s3"], ["AWS"], []),
    "Amazon EC2": ("cloud", ["ec2", "aws ec2"], ["AWS"], []),
    "Amazon SageMaker": ("cloud", ["sagemaker", "aws sagemaker"], ["AWS", "MLOps"], []),
    "Serverless": ("cloud", ["serverless architecture"], [], []),
    "Vercel": ("cloud", [], [], []),
    # ---------------------------------------------------------------- devops
    "Docker": ("devops", ["docker compose", "docker-compose", "containerization", "containers"], [], ["Kubernetes", "Podman"]),
    "Kubernetes": ("devops", ["k8s", "kubernetes cluster"], [], ["Docker", "Helm", "OpenShift"]),
    "Helm": ("devops", [], ["Kubernetes"], []),
    "Terraform": ("devops", ["infrastructure as code", "iac"], [], ["Ansible", "CloudFormation"]),
    "Ansible": ("devops", [], [], ["Terraform"]),
    "CI/CD": ("devops", ["ci cd", "continuous integration", "continuous deployment", "ci/cd pipelines", "cicd"], [], []),
    "GitHub Actions": ("devops", [], ["CI/CD"], ["Jenkins", "GitLab CI"]),
    "Jenkins": ("devops", [], ["CI/CD"], ["GitHub Actions"]),
    "GitLab CI": ("devops", ["gitlab ci/cd"], ["CI/CD"], ["GitHub Actions"]),
    "Git": ("tools", ["github", "gitlab", "version control", "bitbucket"], [], []),
    "Linux": ("devops", ["unix", "ubuntu", "centos", "debian"], [], ["Bash"]),
    "Nginx": ("devops", [], [], []),
    "Prometheus": ("devops", [], ["Monitoring"], ["Grafana"]),
    "Grafana": ("devops", [], ["Monitoring"], ["Prometheus"]),
    "Monitoring": ("devops", ["observability"], [], []),
    "OpenTelemetry": ("devops", ["otel"], ["Monitoring"], []),
    "Kafka": ("data", ["apache kafka"], [], ["RabbitMQ"]),
    "RabbitMQ": ("data", [], [], ["Kafka"]),
    # ---------------------------------------------------------------- AI / ML
    "Machine Learning": ("ai_ml", ["ml", "machine-learning"], [], ["Deep Learning"]),
    "Deep Learning": ("ai_ml", ["dl", "deep neural networks", "neural networks", "neural network"], ["Machine Learning"], []),
    "Natural Language Processing": ("ai_ml", ["nlp", "natural language understanding", "nlu", "text mining"], ["Machine Learning"], []),
    "Computer Vision": ("ai_ml", ["cv", "image processing", "image recognition", "object detection"], ["Machine Learning"], []),
    "Large Language Models": (
        "ai_ml",
        ["llm", "llms", "large language model", "gpt", "generative ai", "genai", "gen ai", "foundation models"],
        ["Natural Language Processing"],
        [],
    ),
    "RAG": (
        "ai_ml",
        ["retrieval augmented generation", "retrieval-augmented generation", "retrieval augmented"],
        ["Large Language Models"],
        ["Vector Databases"],
    ),
    "Prompt Engineering": ("ai_ml", ["prompt design", "prompting"], ["Large Language Models"], []),
    "LLM Fine-tuning": (
        "ai_ml",
        ["fine-tuning", "fine tuning", "finetuning", "lora", "qlora", "peft", "instruction tuning", "rlhf"],
        ["Large Language Models", "Deep Learning"],
        [],
    ),
    "LLM Evaluation": ("ai_ml", ["llm evals", "llm evaluation", "model evaluation", "evals"], ["Large Language Models"], []),
    "AI Agents": ("ai_ml", ["agentic ai", "ai agent", "multi-agent", "multi agent", "autonomous agents", "agents"], ["Large Language Models"], []),
    "LangChain": ("ai_ml", ["lang chain"], ["Large Language Models"], ["LlamaIndex", "LangGraph"]),
    "LangGraph": ("ai_ml", ["lang graph"], ["AI Agents", "Large Language Models"], ["LangChain"]),
    "LlamaIndex": ("ai_ml", ["llama index", "llama-index", "gpt index"], ["Large Language Models", "RAG"], ["LangChain"]),
    "Hugging Face": ("ai_ml", ["huggingface", "hugging face transformers", "transformers library", "hf transformers"], ["Natural Language Processing"], []),
    "Transformers": ("ai_ml", ["transformer models", "transformer architecture", "bert", "attention mechanism"], ["Deep Learning"], []),
    "OpenAI API": ("ai_ml", ["openai", "chatgpt api", "gpt-4", "gpt-4o", "gpt-3.5"], ["Large Language Models"], []),
    "Embeddings": ("ai_ml", ["text embeddings", "sentence embeddings", "sentence-transformers", "sentence transformers", "word embeddings"], ["Natural Language Processing"], []),
    "Semantic Search": ("ai_ml", ["semantic retrieval", "dense retrieval", "neural search"], ["Embeddings"], []),
    "PyTorch": ("ai_ml", ["torch", "pytorch lightning"], ["Deep Learning", "Python"], ["TensorFlow", "JAX"]),
    "TensorFlow": ("ai_ml", ["tensor flow", "tf2"], ["Deep Learning"], ["PyTorch", "Keras"]),
    "Keras": ("ai_ml", [], ["Deep Learning"], ["TensorFlow"]),
    "JAX": ("ai_ml", [], ["Deep Learning"], ["PyTorch"]),
    "scikit-learn": ("ai_ml", ["sklearn", "scikit learn", "scikit"], ["Machine Learning", "Python"], []),
    "XGBoost": ("ai_ml", ["lightgbm", "catboost", "gradient boosting"], ["Machine Learning"], []),
    "OpenCV": ("ai_ml", ["open cv"], ["Computer Vision"], []),
    "YOLO": ("ai_ml", ["yolov5", "yolov8"], ["Computer Vision", "Deep Learning"], []),
    "spaCy": ("ai_ml", ["spacy"], ["Natural Language Processing"], ["NLTK"]),
    "NLTK": ("ai_ml", [], ["Natural Language Processing"], ["spaCy"]),
    "MLOps": ("ai_ml", ["ml ops", "ml pipelines", "model deployment", "model serving"], ["Machine Learning"], []),
    "MLflow": ("ai_ml", ["ml flow"], ["MLOps"], ["Weights & Biases"]),
    "Weights & Biases": ("ai_ml", ["wandb", "weights and biases"], ["MLOps"], ["MLflow"]),
    "vLLM": ("ai_ml", [], ["Large Language Models"], ["Ollama"]),
    "Ollama": ("ai_ml", [], ["Large Language Models"], ["vLLM"]),
    "Reinforcement Learning": ("ai_ml", ["rl", "deep reinforcement learning"], ["Machine Learning"], []),
    "Recommendation Systems": ("ai_ml", ["recommender systems", "recommender system", "recommendation engine"], ["Machine Learning"], []),
    "Statistics": ("data", ["statistical analysis", "statistical modeling", "probability"], [], []),
    # ---------------------------------------------------------------- data
    "Pandas": ("data", [], ["Python", "Data Analysis"], ["Polars"]),
    "NumPy": ("data", ["numpy"], ["Python"], []),
    "Polars": ("data", [], ["Data Analysis"], ["Pandas"]),
    "Apache Spark": ("data", ["spark", "pyspark"], ["Big Data"], ["Hadoop"]),
    "Hadoop": ("data", ["hdfs", "mapreduce"], ["Big Data"], ["Apache Spark"]),
    "Big Data": ("data", [], [], []),
    "Airflow": ("data", ["apache airflow"], ["ETL"], ["Prefect", "Dagster"]),
    "dbt": ("data", ["data build tool"], ["SQL", "ETL"], []),
    "ETL": ("data", ["elt", "etl pipelines", "data pipelines", "data pipeline"], [], []),
    "Data Analysis": ("data", ["data analytics", "analytics", "exploratory data analysis", "eda"], [], []),
    "Data Visualization": ("data", ["data viz", "dashboards", "dashboarding"], [], []),
    "Tableau": ("data", [], ["Data Visualization"], ["Power BI"]),
    "Power BI": ("data", ["powerbi"], ["Data Visualization"], ["Tableau"]),
    "Excel": ("data", ["ms excel", "microsoft excel", "advanced excel"], [], []),
    "Matplotlib": ("data", ["seaborn", "plotly"], ["Data Visualization"], []),
    "Jupyter": ("tools", ["jupyter notebook", "jupyter notebooks", "google colab", "colab"], [], []),
    # ---------------------------------------------------------------- testing
    "Unit Testing": ("testing", ["unit tests", "tdd", "test-driven development", "test driven development"], [], []),
    "Pytest": ("testing", ["pytest"], ["Unit Testing", "Python"], []),
    "Jest": ("testing", [], ["Unit Testing", "JavaScript"], []),
    "Playwright": ("testing", [], [], ["Selenium", "Cypress"]),
    "Selenium": ("testing", [], [], ["Playwright"]),
    "Cypress": ("testing", [], [], ["Playwright"]),
    # ---------------------------------------------------------------- tools / methods
    "Agile": ("methodologies", ["scrum", "kanban", "agile methodologies"], [], []),
    "Jira": ("tools", [], [], []),
    "System Design": ("methodologies", ["distributed systems", "scalable systems", "software architecture"], [], []),
    "Data Structures and Algorithms": ("methodologies", ["dsa", "data structures", "algorithms"], [], []),
    "Object-Oriented Programming": ("methodologies", ["oop", "oops", "object oriented programming", "object-oriented design"], [], []),
    "Web Scraping": ("tools", ["beautifulsoup", "scrapy"], [], []),
    "Postman": ("tools", [], ["REST APIs"], []),
    "Streamlit": ("frameworks", [], ["Python"], ["Gradio"]),
    "Gradio": ("frameworks", [], ["Python"], ["Streamlit"]),
    "WebSockets": ("frameworks", ["websocket", "socket.io"], [], []),
    "OAuth": ("tools", ["oauth2", "oauth 2.0", "jwt", "authentication"], [], []),
    "Security": ("methodologies", ["application security", "appsec", "cybersecurity", "owasp"], [], []),
}

# Aliases that must match case-sensitively (too ambiguous otherwise).
CASE_SENSITIVE_ALIASES: dict[str, str] = {
    "Go": "Go",
    "R": "R",
    "C": "C",
    "ML": "Machine Learning",
    "CV": "Computer Vision",
    "DL": "Deep Learning",
    "RL": "Reinforcement Learning",
    "TS": "TypeScript",
    "JS": "JavaScript",
}

# Case-insensitive aliases that are only trusted inside skill lists (comma/pipe separated),
# because in prose they collide with ordinary English words.
LIST_ONLY_ALIASES = {"py", "go", "r", "c", "ml", "cv", "dl", "rl", "ts", "js", "rest", "shell", "cloud", "spring",
                     "express", "node", "agents", "evals", "oracle", "lambda", "analytics", "containers", "spark",
                     "torch", "vue", "rails", "tailwind", "chroma", "scikit", "authentication", "dashboards",
                     "probability", "algorithms", "data structures", "prompting", "gpt", "openai"}

SOFT_SKILLS = [
    "communication",
    "teamwork",
    "collaboration",
    "leadership",
    "problem solving",
    "problem-solving",
    "critical thinking",
    "time management",
    "adaptability",
    "ownership",
    "mentoring",
    "stakeholder management",
    "attention to detail",
    "self-motivated",
    "analytical skills",
]

CATEGORY_LABELS = {
    "programming": "Programming Languages",
    "frameworks": "Frameworks & APIs",
    "frontend": "Frontend & Mobile",
    "databases": "Databases",
    "cloud": "Cloud",
    "devops": "DevOps & Infrastructure",
    "ai_ml": "AI / ML",
    "data": "Data",
    "testing": "Testing",
    "tools": "Tools",
    "methodologies": "Practices",
    "other": "Other",
}
