"""initial schema

Revision ID: 6f78f7abfcaa
Revises: 
Create Date: 2026-09-25 22:55:19.583604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f78f7abfcaa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('token_usage_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_candidate_id'), 'agent_runs', ['candidate_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('job_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('candidate_preferences',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('preferences_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_preferences_user_id'), 'candidate_preferences', ['user_id'], unique=True)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_resume_text', sa.Text(), nullable=True),
    sa.Column('resume_hash', sa.String(length=64), nullable=True),
    sa.Column('structured_profile_json', sa.JSON(), nullable=False),
    sa.Column('parse_warnings_json', sa.JSON(), nullable=False),
    sa.Column('last_discovery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.create_table('event_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_tasks_dedup_key'), 'event_tasks', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_event_tasks_event_type'), 'event_tasks', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_tasks_run_after'), 'event_tasks', ['run_after'], unique=False)
    op.create_index(op.f('ix_event_tasks_status'), 'event_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_event_tasks_user_id'), 'event_tasks', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('work_mode', sa.String(length=32), nullable=True),
    sa.Column('employment_type', sa.String(length=32), nullable=True),
    sa.Column('seniority', sa.String(length=32), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_truncated', sa.Boolean(), nullable=False),
    sa.Column('application_url', sa.String(length=1024), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('duplicate_of_id', sa.String(length=32), nullable=True),
    sa.Column('alternate_sources_json', sa.JSON(), nullable=False),
    sa.Column('analysis_hash', sa.String(length=64), nullable=True),
    sa.Column('jd_analysis_json', sa.JSON(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_jobs_source_external')
    )
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_jobs_duplicate_of_id'), 'jobs', ['duplicate_of_id'], unique=False)
    op.create_index(op.f('ix_jobs_fingerprint'), 'jobs', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('skill', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('proficiency', sa.String(length=32), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_id'), 'candidate_skills', ['candidate_id'], unique=False)
    op.create_table('jd_requirements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('requirement', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('source_span', sa.Text(), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('extracted_by', sa.String(length=16), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jd_requirements_job_id'), 'jd_requirements', ['job_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('role_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('location_score', sa.Float(), nullable=False),
    sa.Column('education_score', sa.Float(), nullable=False),
    sa.Column('preference_score', sa.Float(), nullable=False),
    sa.Column('seniority_score', sa.Float(), nullable=False),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('hard_filter_passed', sa.Boolean(), nullable=False),
    sa.Column('hard_filter_reasons_json', sa.JSON(), nullable=False),
    sa.Column('matched_skills_json', sa.JSON(), nullable=False),
    sa.Column('missing_skills_json', sa.JSON(), nullable=False),
    sa.Column('breakdown_json', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_source', sa.String(length=16), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('resume_compatibility', sa.Float(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_job_match')
    )
    op.create_index(op.f('ix_job_matches_candidate_id'), 'job_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_table('job_skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('skill', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_skills_job_id'), 'job_skills', ['job_id'], unique=False)
    op.create_table('resume_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('layout_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_files_candidate_id'), 'resume_files', ['candidate_id'], unique=False)
    op.create_table('requirement_matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('requirement_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['jd_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'candidate_id', name='uq_reqmatch')
    )
    op.create_index(op.f('ix_requirement_matches_candidate_id'), 'requirement_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_requirement_matches_requirement_id'), 'requirement_matches', ['requirement_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('parent_version_id', sa.String(length=32), nullable=True),
    sa.Column('resume_file_id', sa.String(length=32), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('pdf_path', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('quality_index', sa.Float(), nullable=True),
    sa.Column('parser_score', sa.Float(), nullable=True),
    sa.Column('keyword_score', sa.Float(), nullable=True),
    sa.Column('requirement_score', sa.Float(), nullable=True),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('round_trip_score', sa.Float(), nullable=True),
    sa.Column('formatting_score', sa.Float(), nullable=True),
    sa.Column('last_report_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_file_id'], ['resume_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_candidate_id'), 'resume_versions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resume_versions_job_id'), 'resume_versions', ['job_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_url', sa.String(length=1024), nullable=True),
    sa.Column('resume_version_id', sa.String(length=32), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('cover_letter_source', sa.String(length=16), nullable=True),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('package_json', sa.JSON(), nullable=False),
    sa.Column('submission_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_application_candidate_job')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_table('resume_claims',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resume_version_id', sa.String(length=32), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_claims_resume_version_id'), 'resume_claims', ['resume_version_id'], unique=False)
    op.create_table('resume_tests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resume_version_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('test_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_tests_resume_version_id'), 'resume_tests', ['resume_version_id'], unique=False)
    op.create_index(op.f('ix_resume_tests_run_id'), 'resume_tests', ['run_id'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_resume_tests_run_id'), table_name='resume_tests')
    op.drop_index(op.f('ix_resume_tests_resume_version_id'), table_name='resume_tests')
    op.drop_table('resume_tests')
    op.drop_index(op.f('ix_resume_claims_resume_version_id'), table_name='resume_claims')
    op.drop_table('resume_claims')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_resume_versions_job_id'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_candidate_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_requirement_matches_requirement_id'), table_name='requirement_matches')
    op.drop_index(op.f('ix_requirement_matches_candidate_id'), table_name='requirement_matches')
    op.drop_table('requirement_matches')
    op.drop_index(op.f('ix_resume_files_candidate_id'), table_name='resume_files')
    op.drop_table('resume_files')
    op.drop_index(op.f('ix_job_skills_job_id'), table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_candidate_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_jd_requirements_job_id'), table_name='jd_requirements')
    op.drop_table('jd_requirements')
    op.drop_index(op.f('ix_candidate_skills_candidate_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_fingerprint'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_duplicate_of_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_content_hash'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_event_tasks_user_id'), table_name='event_tasks')
    op.drop_index(op.f('ix_event_tasks_status'), table_name='event_tasks')
    op.drop_index(op.f('ix_event_tasks_run_after'), table_name='event_tasks')
    op.drop_index(op.f('ix_event_tasks_event_type'), table_name='event_tasks')
    op.drop_index(op.f('ix_event_tasks_dedup_key'), table_name='event_tasks')
    op.drop_table('event_tasks')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_candidate_preferences_user_id'), table_name='candidate_preferences')
    op.drop_table('candidate_preferences')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_runs_candidate_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
